### ISSUE TITLE
Setup.py references a requirements.txt, failing with pip install

### ISSUE THREAD

**Issue by Giddius** [jorgeajimenezl/aiodav#1]
Trying to install via `pip install aiodav`

Fails with the following error:
```shell
    ERROR: Command errored out with exit status 1:
     command: '************\.venv\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'**********\\AppData\\Local\\Temp\\pip-install-9sh87emp\\aiodav_c7227b5884ae4053bb9b6198ed8e8259\\setup.py'"'"'; __file__='"'"'*********i\\AppData\\Local\\Temp\\pip-install-9sh87emp\\aiodav_c7227b5884ae4053bb9b6198ed8e8259\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base '******\AppData\Local\Temp\pip-pip-egg-info-flj8t2e0'
         cwd: *******\Local\Temp\pip-install-9sh87emp\aiodav_c7227b5884ae4053bb9b6198ed8e8259\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "******\AppData\Local\Temp\pip-install-9sh87emp\aiodav_c7227b5884ae4053bb9b6198ed8e8259\setup.py", line 8, in <module>
        with open('requirements.txt', 'r') as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/16/77e9a49d7dd950ece3759fdce919f4e5b85b7952c8bc2c63edc1dcb44a60/aiodav-0.1.1.tar.gz#sha256=964a0ffb30f6aa1aabd76d8afa6f875752d0b7bb079c12d1538e52bb6ce64a76 (from https://pypi.org/simple/aiodav/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement aiodav (from versions: 0.1.1)
ERROR: No matching distribution found for aiodav
```

Propably creating wheels would fix that.

**Comment by jorgeajimenezl** [comment]
Please try again now, I still don't know what exactly happens. Tried it a few minutes ago and that works fine for me.
```shell
(env)  ~/Documents/repos/aiodav_test -> pip install aiodav
Collecting aiodav
  Downloading aiodav-0.1.4-py3-none-any.whl (13 kB)
Collecting aiofiles
  Using cached aiofiles-0.6.0-py3-none-any.whl (11 kB)
Collecting aiodns
  Using cached aiodns-2.0.0-py2.py3-none-any.whl (4.8 kB)
Collecting cchardet
  Using cached cchardet-2.1.7-cp39-cp39-manylinux2010_x86_64.whl (265 kB)
Collecting aiohttp
  Using cached aiohttp-3.7.4.post0-cp39-cp39-manylinux2014_x86_64.whl (1.4 MB)
Collecting lxml
  Downloading lxml-4.6.3-cp39-cp39-manylinux2014_x86_64.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 102 kB/s 
Collecting pycares>=3.0.0
  Downloading pycares-3.2.3-cp39-cp39-manylinux2010_x86_64.whl (258 kB)
     |████████████████████████████████| 258 kB 101 kB/s 
Collecting cffi>=1.5.0
  Using cached cffi-1.14.5-cp39-cp39-manylinux1_x86_64.whl (406 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.1.0-cp39-cp39-manylinux2014_x86_64.whl (151 kB)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.6.3-cp39-cp39-manylinux2014_x86_64.whl (315 kB)
Collecting chardet<5.0,>=2.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting attrs>=17.3.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 107 kB/s 
Collecting idna>=2.0
  Downloading idna-3.1-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 120 kB/s 
Installing collected packages: pycparser, multidict, idna, cffi, yarl, typing-extensions, pycares, chardet, attrs, async-timeout, lxml, cchardet, aiohttp, aiofiles, aiodns, aiodav
Successfully installed aiodav-0.1.4 aiodns-2.0.0 aiofiles-0.6.0 aiohttp-3.7.4.post0 async-timeout-3.0.1 attrs-21.2.0 cchardet-2.1.7 cffi-1.14.5 chardet-4.0.0 idna-3.1 lxml-4.6.3 multidict-5.1.0 pycares-3.2.3 pycparser-2.20 typing-extensions-3.10.0.0 yarl-1.6.3
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/home/jorgeajimenezl/Documents/repos/aiodav_test/env/bin/python -m pip install --upgrade pip' command.
(env)  ~/Documents/repos/aiodav_test ->
```
Thank you for your observation

**Comment by Giddius** [comment]
Works now!
